// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiIQz-OzI10tJOakF09lyVUa83vKZfmoE',
    appId: '1:267770869749:web:e29bfbd6903bdb2aa712bc',
    messagingSenderId: '267770869749',
    projectId: 'flutter-smart-save',
    authDomain: 'flutter-smart-save.firebaseapp.com',
    storageBucket: 'flutter-smart-save.firebasestorage.app',
    measurementId: 'G-C56RHWQLHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRzSXIH2ndSdEqRCp6_MfiPRS0tM0Od4',
    appId: '1:267770869749:android:4899f67b54e2e762a712bc',
    messagingSenderId: '267770869749',
    projectId: 'flutter-smart-save',
    storageBucket: 'flutter-smart-save.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7bOisXqtVwnTYkhbkgSATWhbHOqPtJWQ',
    appId: '1:267770869749:ios:7942f14505148ec0a712bc',
    messagingSenderId: '267770869749',
    projectId: 'flutter-smart-save',
    storageBucket: 'flutter-smart-save.firebasestorage.app',
    iosClientId: '267770869749-uoe2bu2p8fsi0lm8sg9qimqd787iqm2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.savesmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7bOisXqtVwnTYkhbkgSATWhbHOqPtJWQ',
    appId: '1:267770869749:ios:7942f14505148ec0a712bc',
    messagingSenderId: '267770869749',
    projectId: 'flutter-smart-save',
    storageBucket: 'flutter-smart-save.firebasestorage.app',
    iosClientId: '267770869749-uoe2bu2p8fsi0lm8sg9qimqd787iqm2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.savesmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiIQz-OzI10tJOakF09lyVUa83vKZfmoE',
    appId: '1:267770869749:web:28b9e81ea15fd440a712bc',
    messagingSenderId: '267770869749',
    projectId: 'flutter-smart-save',
    authDomain: 'flutter-smart-save.firebaseapp.com',
    storageBucket: 'flutter-smart-save.firebasestorage.app',
    measurementId: 'G-L3QF7JS2ZD',
  );

}